<?php
/**
 * @file
 * Code for the Futurium data model feature.
 */

include_once 'futurium_data.features.inc';

/**
 * Sets feature api version.
 *
 * @return array
 *   version
 */
function futurium_data_feature_set_api() {
  return array('version' => '1.0');
}

/**
 * Implements hook_node_form_alter().
 */
function futurium_data_form_node_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'ideas_node_form' && !user_access('access custom futurium fields')) {
    field_group_hide_field_groups($form, array('group_related_content'));
  }
}
